use_frameworks!

target 'PanTilt_Example' do
  pod 'PanTilt', :path => '../'

  target 'PanTilt_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
    pod 'Nimble', '~> 7.3.1'
  end
end
