use_frameworks!

target 'PanTilt_Example' do
  pod 'PanTilt', :path => '../'

  target 'PanTilt_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
