use_frameworks!


target 'PanTilt_Example' do
  platform :ios, '12.0'
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        config.build_settings.delete 'ARCHS'
      end
    end
  end
  pod 'PanTilt', :path => '../'

  target 'PanTilt_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
